#!/bin/sh

[ -z $NGINX_WORKER_PROCESSES ] && export NGINX_WORKER_PROCESSES=auto
[ -z $NGINX_WORKER_CONNECTIONS ] && export NGINX_WORKER_CONNECTIONS=1024
[ -z $NGINX_KEEPALIVE_TIMEOUT ] && export NGINX_KEEPALIVE_TIMEOUT=1
[ -z $NGINX_DEFAULT_PORT ] && export NGINX_DEFAULT_PORT=80
[ -z $NGINX_APP_NAME ] && export NGINX_APP_NAME=pastefile

envsubst '$NGINX_WORKER_PROCESSES $NGINX_WORKER_CONNECTIONS $NGINX_KEEPALIVE_TIMEOUT' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
envsubst '$NGINX_DEFAULT_PORT $NGINX_APP_NAME $UWSGI_SOCK' < /etc/nginx/vhost.conf.template > /etc/nginx/conf.d/default.conf
nginx -g "daemon off;"
